### ISSUE TITLE
Remove references to util

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js-navigator#15]
Required for 2.5

**Comment by melborp** [comment]
i have already hit this and also i think i created a separate issue.
Whats necessary to avoid the following error:

Uncaught TypeError: Cannot read property 'requestAnimationFrame' of undefined
Navigator._updateThumbnailImage @ cytoscape.js-navigator.js:548
Navigator._setupThumbnail @ cytoscape.js-navigator.js:138
Navigator._initThumbnail @ cytoscape.js-navigator.js:116
(anonymous function) @ cytoscape.js-navigator.js:36
triggerImpl @ cytoscape.js:8341
(anonymous function) @ cytoscape.js:6615
triggerImpl @ cytoscape.js:8341
(anonymous function) @ cytoscape.js:5795
triggerImpl @ cytoscape.js:8341
triggerImpl @ cytoscape.js:8365
elesfn.layoutPositions @ cytoscape.js:4693
DagreLayout.run @ cytoscape-dagre.js:162
corefn.layout @ cytoscape.js:6910
callback @ cytoscape.js:5804

**Comment by melborp** [comment]
Apologies. I reported this in wrong location: 
https://github.com/cytoscape/cytoscape.js-dagre/issues/2

Moving 
```

    var raf = !window ? null : (window.requestAnimationFrame || window.mozRequestAnimationFrame || window.webkitRequestAnimationFrame || window.msRequestAnimationFrame);

    raf = raf || function (fn) { if (fn) { setTimeout(fn, 1000 / 60); } };

    var requestAnimationFrame = function(fn) {
        raf(fn);
    }
```

from cytoscape 2.5 to the navigator code and then calling it doesnt seem to be enough to make navigator work. 
```
        //cytoscape.util.requestAnimationFrame( render );
        requestAnimationFrame(render);
    }

      //cytoscape.util.requestAnimationFrame( render );
    requestAnimationFrame(render);
```

**Comment by melborp** [comment]
actually, it does work after moving the same code to the navigator. So this would be a workaround or perhaps the solution.

´´´
  , _updateThumbnailImage: function (force_refresh) {
    var that = this;

    if( this._thumbnailUpdating ){
      return;
    }

    this._thumbnailUpdating = true;

    var raf = !window ? null : (window.requestAnimationFrame || window.mozRequestAnimationFrame || window.webkitRequestAnimationFrame || window.msRequestAnimationFrame);

    raf = raf || function (fn) { if (fn) { setTimeout(fn, 1000 / 60); } };

    var requestAnimationFrame = function(fn) {
        raf(fn);
    }

    var render = function(){
      var canvas = that.$thumbnail[0];
      var cxt = canvas.getContext('2d');

      var w = that.panelWidth;
      var h = that.panelHeight;
      var bb = that.boundingBox;
      var zoom = Math.min(w/bb.w, h/bb.h);
      var pxRatio = 1;
      var pan = {
        x: (w - zoom*( bb.x1 + bb.x2 ))/2,
        y: (h - zoom*( bb.y1 + bb.y2 ))/2
      };


      cxt.setTransform(1, 0, 0, 1, 0, 0);
      cxt.clearRect(0, 0, w, h);

      // Copy scaled thumbnail to buffer
      that.cy.renderTo(cxt, zoom, pan, pxRatio);

        //cytoscape.util.requestAnimationFrame( render );
        requestAnimationFrame(render);
    }

      //cytoscape.util.requestAnimationFrame( render );
    requestAnimationFrame(render);

  }
´´´

**Comment by kmicinski** [comment]
This issue currently breaks Cytoscape.js-navigator, when used with current releases of cytoscape.js and cytoscape.js-dagre. However, the suggested fix works for me. Is there a reason it hasn't been applied? Otherwise cytoscape.js-navigator is essentially broken until you know which issue to look for.

**Comment by maxkfranz** [comment]
@bumbu Hi Alex, would you be able to take a look where/if this is using `util` in your extension?  Thanks

**Comment by kmicinski** [comment]
As far as I can tell, `cytoscape.js-navigator` only uses `util` in the two places pointed out by @melborp.

**Comment by maxkfranz** [comment]
This looks like it should resolve it: https://github.com/cytoscape/cytoscape.js-navigator/pull/16

**Comment by maxkfranz** [comment]
Updated and tagged as 1.0.2
