### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by antjkennedy** [cytoscape/cytoscape.js-navigator#17]
Just a quick note on licensing [jquery.json](https://github.com/cytoscape/cytoscape.js-navigator/blob/master/cytoscape.js-navigator.jquery.json) and [bower.json](https://github.com/cytoscape/cytoscape.js-navigator/blob/master/bower.json) specify differenct licenses for the library, LGPLv3 and MIT respectivly, is this intentional?

**Comment by maxkfranz** [comment]
The jquery one is old.  The jquery.json should probably just be deleted
