### ISSUE TITLE
When all elements are deleted from cy, navigator shows broken link image.

### ISSUE THREAD

**Issue by istemi-bahceci** [cytoscape/cytoscape.js-navigator#24]
![image](https://cloud.githubusercontent.com/assets/8645080/16662944/b59d13e0-4482-11e6-8941-022a70d72b2b.png)

As you can see above, when there is no element in cytoscape.js instance, a broken link image is shown in navigator.

**Comment by maxkfranz** [comment]
Does that commit sort it?

**Comment by istemi-bahceci** [comment]
It seems OK now, thanks for the  fix @maxkfranz :) Are you planning to make a release on npm ?

**Comment by maxkfranz** [comment]
OK, if it works then 1.1.3 will be published
