### ISSUE TITLE
must include $ when registering

### ISSUE THREAD

**Issue by ajoslin103** [cytoscape/cytoscape.js-navigator#28]
Using this library in an Aurelia application I find that I must register it with the jquery param or it fails to work.

works ok: navigator( cytoscape, $ );

doesn't work: navigator( cytoscape );

(love it, btw!)

**Comment by maxkfranz** [comment]
If you use AMD, you have to specify everything yourself.

**Comment by ajoslin103** [comment]
yes, I figured that out - only noted it in case you wanted to tweak the docs

**Comment by maxkfranz** [comment]
@mj3cheun Could you update the readme when you publish the extensions updates?
