### ISSUE TITLE
Navigator thumb does not display all elements when using the browsers zooming function

### ISSUE THREAD

**Issue by newtask** [cytoscape/cytoscape.js-navigator#29]
The navigator works fine when the zoom level is at 100%. When you zoom into the webpage the navigator doesn't display all elements.
![navigator](https://user-images.githubusercontent.com/2364855/27867216-56c43bde-6199-11e7-9cc0-68f5a1bfc44c.PNG)

**Comment by maxkfranz** [comment]
Works fine for me in Chrome and Firefox
