### ISSUE TITLE
jQuery is not defined error

### ISSUE THREAD

**Issue by israel-hdez** [cytoscape/cytoscape.js-navigator#36]
I wanted to use the navigator in a React app. I guess in a React app the module gets defined as a CommonJs module.

When initializing the navigator, if I set a container, I get "jQuery is not defined" error.

I guess the `_initPanel` function is referencing the global jQuery object rather than using the local `$` variable.

**Comment by maxkfranz** [comment]
It should `require('jquery')` unless you already are using globals: https://github.com/cytoscape/cytoscape.js-navigator/blob/master/cytoscape-navigator.js#L886

**Comment by israel-hdez** [comment]
Not sure if this helps, but for me, it fails here:
https://github.com/cytoscape/cytoscape.js-navigator/blob/master/cytoscape-navigator.js#L364

**Comment by maxkfranz** [comment]
@israel-hdez Does 0006766 resolve it for you?

**Comment by israel-hdez** [comment]
@maxkfranz Yes, it's solved.

**Comment by maxkfranz** [comment]
Published 1.3.3
