### ISSUE TITLE
Problem using navigator and toolbar extensions

### ISSUE THREAD

**Issue by chinicuin** [cytoscape/cytoscape.js-navigator#37]
Hello.
I trying to use navigator and toolbar (https://github.com/bdparrish/cytoscape.js-toolbar) extensions at the same time but when I  do that, can't see neither one.
Is even possible to use both extensions together?
Thanks in advance for the answer.

**Comment by palvarezcordoba** [comment]
Hi @chinicuin 
First of all, I think you should (and need to) read this article: http://www.catb.org/esr/faqs/smart-questions.html

Ok, now: There is some error in the console log? Give more information.
I am also going to try this extension in conjunction to toolbar

**Comment by chinicuin** [comment]
Thank you.
Already solved the problem. Both extensions can be used at the same time.
