### ISSUE TITLE
container doesn't seem to work in 2.0.1

### ISSUE THREAD

**Issue by alhuber1502** [cytoscape/cytoscape.js-navigator#48]
It appears that the container setting is ignored in 2.0.1. It always appears to default to a fixed position outside of any container.  Works fine in 1.3.3.

**Comment by maxkfranz** [comment]
Please provide a reproducible test case, including:

- Browser version
- OS version
- A code sample that reproduces the issue.  [A JSBin](http://jsbin.com/fiqugiq) can be forked to easily provide a code sample.
