### ISSUE TITLE
Not connecting to container

### ISSUE THREAD

**Issue by Alexithemia** [cytoscape/cytoscape.js-navigator#52]
Hello! Not sure if I am not setting this up correctly, but the navigator is not getting attached under the correct container. It is going under the html body element no matter what I specify in options.

It also does not have any height or the correct positioning, which could be due to not having the correct container?

```
this.cy.navigator({
      container: this.cy.container(),
      viewLiveFramerate: 0,
      thumbnailEventFramerate: 30,
      thumbnailLiveFramerate: false,
      dblClickDelay: 200,
      removeCustomContainer: true,
      rerenderDelay: 100
    });
```

![image](https://user-images.githubusercontent.com/44597137/144484841-353f459e-82fe-4030-8bb6-6814ef6774f3.png)

**Comment by maxkfranz** [comment]
Closed via #54
