### ISSUE TITLE
Options don't accept HTML element as container

### ISSUE THREAD

**Issue by r0manchak** [cytoscape/cytoscape.js-navigator#53]
Hi,
Thanks for the lib.

Looking at the `_initPanel` method it checks if the container is a string and creates a new one if it's not.
When providing an HTML element instead it's not honored

![image](https://user-images.githubusercontent.com/4974042/149172590-76b8fef7-d6d6-4188-9e89-55df1f338aa8.png)

**Comment by maxkfranz** [comment]
There have been PRs over time that have added options for how container handling is done.  It's probably not ideal how it's functioning now.

I believe that most use cases would be served by using the defaults w.r.t. the container.  I don't think there should be an option for the container at all and it should just be automatic, though you're welcome to enhance things further in a PR if you like

**Comment by matthias-ccri** [comment]
I noticed the same thing. The README is incorrect:
```
container: false // html dom element
```
It should be something like:
```
container: false // an ID string like "#someId" or className selector like ".someClassName". If false or undefined, an element will be created.
```

**Comment by matthias-ccri** [comment]
How does this look: https://github.com/cytoscape/cytoscape.js-navigator/pull/54/files
