### ISSUE TITLE
infinite loop

### ISSUE THREAD

**Issue by quatrano** [cytoscape/cytoscape.js-navigator#8]
I noticed that the render() function is called periodically forever, even if the navigator is destroy()ed because of this line:
https://github.com/cytoscape/cytoscape.js-navigator/blob/master/cytoscape.js-navigator.js#L540

This is fine when you instantiate the navigator once, but if you instantiate the navigator more than once, these infinite loops pile up, and eventually consume 100% CPU.  

In my project I've overridden window.requestAnimationFrame() so I can break this loop, but it would be nice if, when the navigator is destroy()ed, this loop were interrupted.

**Comment by markov00** [comment]
I've see the same problem, the CPU goes to 100% even if I've instantiated only one time the navigator.
I've checked the code and I was thinking of this: why are we using requestAnimationFrame? 
We only need to render the navigator viewport when element events happen on the graph. 

The navigator already setup a listener to those events thanks to the  **_hookGraphUpdates**.
Removing the requestAnimationFrame loop, we can call _updateThumbnailImage method only when a specific event occur avoiding unnecessary frames. 

If we add also the **style** event to the listener we have the complete set of events that needs to be catch on the navigator.
What do you think?

**Comment by maxkfranz** [comment]
I think you'd need at least `viewport, add, remove, style` events.  It may not be quite as fast as the other option, but it would work with 2.3.x instead of waiting on 2.4.
