### ISSUE TITLE
Ghost images

### ISSUE THREAD

**Issue by jeremychapman** [cytoscape/cytoscape.js-navigator#9]
Has anyone noticed that if you drag nodes or parent nodes around, after you drop them the there are faded 'ghost' images of the nodes and edges at the original locations?

This also happens when you zoom in/out
![cytoscape nav capture](https://cloud.githubusercontent.com/assets/2073060/5551162/e5b9ce62-8b72-11e4-85b9-abf2f4e7efb2.JPG)

**Comment by maxkfranz** [comment]
Refer to https://github.com/cytoscape/cytoscape.js/issues/791
